### ISSUE TITLE
rollover window can close during resize mouse drag

### ISSUE THREAD

**Issue by akstuhl** [performant-software/DM#105]
The user should be able to resize the rollover window by dragging its corner without the mouse position accidentally triggering a rollover window close.

**Comment by SteveMarvin** [comment]
This seems to work fine, as long as we intend here for the window to close only when the mouse pointer exits the popup boundary. Since the drag point is set rather deeply into the popup, and is not at the actual outer corner of the popup, this seems fine.
![screen shot 2017-05-04 at 11 45 36 am](https://cloud.githubusercontent.com/assets/18423533/25712370/6ed8a1d4-30bf-11e7-9a31-8d2a3df28b43.png)

However, if the popup should be staying present even after the mouse pointer leaves the popup window, then that is not the case. The popup closes almost immediately after the pointer leaves the popup.
