### ISSUE TITLE
Installation error by using DigitalOcean services

### ISSUE THREAD

**Issue by yifanpeng** [performant-software/DM#186]
We had a problem when using Digital Ocean Services. After setting configuration variables, we try to install the DM by packer. It showed the error message (please refer to the attachment). Could anyone give us a hint about install the DM? Thank you.

![2018-07-02_174422](https://user-images.githubusercontent.com/5918286/42157550-9370dd04-7e20-11e8-985d-1b8492f737d5.png)

**Comment by NickLaiacona** [comment]
The issue was that the deployment process required the user to build DM from source, but it doesn't say that in the instructions. Checking build artifacts into the development repository is also not a great solution, so I've created a new repository where DM Digital Ocean deployment now lives. It can be found here: https://github.com/performant-software/dm-digitalocean . This repo will always contain the latest stable build.

So please try again using  https://github.com/performant-software/dm-digitalocean .
